// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://subitzcorydmzkqqbrtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Yml0emNvcnlkbXprcXFicnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTQyMDUsImV4cCI6MjA3MDczMDIwNX0.JLRHQRSEotPe7_9oOp8T3RoV5Gtyh0urN8XFERjY1-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});